# Generated by Django 5.2.5 on 2025-08-08 18:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(help_text='Phần hiển thị trên URL, không dấu, không khoảng trắng. VD: nhan-kim-cuong', max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Các danh mục',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề bài viết')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Ảnh bìa')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đăng')),
                ('author', models.CharField(default='BJF', max_length=100, verbose_name='Tác giả')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Các bài viết',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá tiền (VND)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Hình ảnh')),
                ('is_available', models.BooleanField(default=True, verbose_name='Đang bán?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Các sản phẩm',
            },
        ),
    ]
