# Generated by Django 4.2.23 on 2025-09-03 07:59

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Câu Chuyện Về BJF', max_length=200, verbose_name='Tiêu đề chính')),
                ('hero_subtitle', models.CharField(default='Nơi mỗi tuyệt tác không chỉ là trang sức, mà là di sản của đam mê và sự tinh xảo.', max_length=300, verbose_name='Tiêu đề phụ')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Ảnh nền Hero')),
                ('philosophy_tagline', models.CharField(default='Triết Lý Của Chúng Tôi', max_length=100, verbose_name='Dòng giới thiệu Triết lý')),
                ('philosophy_title', models.CharField(default='Tôn Vinh Vẻ Đẹp Vĩnh Cửu', max_length=200, verbose_name='Tiêu đề Triết lý')),
                ('philosophy_content', models.TextField(default='Tại BJF, chúng tôi tin rằng trang sức là ngôn ngữ của cảm xúc...', verbose_name='Nội dung Triết lý')),
                ('philosophy_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Ảnh Triết lý')),
                ('history_title', models.CharField(default='Dấu Ấn Qua Từng Thời Kỳ', max_length=200, verbose_name='Tiêu đề Lịch sử')),
                ('history_subtitle', models.CharField(default='Hơn hai thập kỷ không ngừng nỗ lực để xây dựng một thương hiệu trang sức Việt Nam uy tín và đẳng cấp.', max_length=300, verbose_name='Tiêu đề phụ Lịch sử')),
                ('milestone1_year', models.CharField(default='2005: Khởi Đầu Đam Mê', max_length=50, verbose_name='Cột mốc 1 - Năm & Tiêu đề')),
                ('milestone1_text', models.TextField(default='BJF ra đời từ một xưởng chế tác nhỏ...', verbose_name='Cột mốc 1 - Nội dung')),
                ('milestone1_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Cột mốc 1 - Ảnh')),
                ('milestone2_year', models.CharField(default='2015: Khẳng Định Vị Thế', max_length=50, verbose_name='Cột mốc 2 - Năm & Tiêu đề')),
                ('milestone2_text', models.TextField(default='Trở thành một trong những thương hiệu được tin cậy hàng đầu...', verbose_name='Cột mốc 2 - Nội dung')),
                ('milestone2_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Cột mốc 2 - Ảnh')),
                ('milestone3_year', models.CharField(default='2025: Vươn Ra Thế Giới', max_length=50, verbose_name='Cột mốc 3 - Năm & Tiêu đề')),
                ('milestone3_text', models.TextField(default='Ra mắt nền tảng thương mại điện tử...', verbose_name='Cột mốc 3 - Nội dung')),
                ('milestone3_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Cột mốc 3 - Ảnh')),
                ('craftsmanship_title', models.CharField(default='Nghệ Thuật Chế Tác Đỉnh Cao', max_length=200, verbose_name='Tiêu đề Chế tác')),
                ('craftsmanship_subtitle', models.CharField(default='Mỗi sản phẩm là một bản giao hưởng của vật liệu quý hiếm và bàn tay tài hoa của nghệ nhân.', max_length=300, verbose_name='Tiêu đề phụ Chế tác')),
            ],
            options={
                'verbose_name': 'Trang Về Chúng Tôi',
            },
        ),
        migrations.CreateModel(
            name='ActionButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_type', models.CharField(choices=[('zalo', 'Zalo'), ('phone', 'Gọi điện')], max_length=10, verbose_name='Loại nút')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Nút hành động',
                'verbose_name_plural': 'Các nút hành động',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('image', 'Hình ảnh'), ('video', 'Video')], default='image', max_length=10, verbose_name='Loại banner')),
                ('image', models.ImageField(blank=True, help_text="Tải lên nếu loại banner là 'Hình ảnh'.", null=True, upload_to='banners/', verbose_name='Hình ảnh banner')),
                ('video_url', models.URLField(blank=True, help_text="Dán link EMBED vào đây nếu loại banner là 'Video'. Ví dụ: https://www.youtube.com/embed/your_video_id", null=True, verbose_name='Đường dẫn Video (YouTube/Vimeo Embed)')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề chính (tùy chọn)')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề phụ (tùy chọn)')),
                ('link', models.URLField(blank=True, verbose_name='Đường dẫn (tùy chọn)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị, số nhỏ hơn hiện trước', verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Các Banner',
                'ordering': ['order'],
                'permissions': [('manage_banner', 'Có thể quản lý toàn bộ Banner')],
            },
        ),
        migrations.CreateModel(
            name='BatDongSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tai_san', models.CharField(max_length=50, unique=True, verbose_name='ID tài sản')),
                ('dia_chi', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('google_maps_link', models.URLField(blank=True, null=True, verbose_name='Link Google Maps')),
                ('chi_tiet_su_dung_dat', models.CharField(help_text='Ví dụ: Đất thổ cư 5100 m2', max_length=255, verbose_name='Chi tiết sử dụng đất')),
                ('mat_tien', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mặt tiền (m)')),
                ('chieu_sau', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chiều sâu (m)')),
                ('huong', models.CharField(blank=True, max_length=50, verbose_name='Hướng')),
                ('phap_ly', models.CharField(default='Sổ đỏ/Sổ hồng', max_length=100, verbose_name='Pháp lý')),
                ('tinh_trang_xay_dung', models.CharField(default='Đất trống', max_length=100, verbose_name='Tình trạng xây dựng')),
                ('hien_trang_su_dung', models.TextField(blank=True, verbose_name='Hiện trạng sử dụng')),
                ('gia_rao_cam_co', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Giá chủ nhà rao cầm cố (VNĐ)')),
                ('gia_chot_ky_vong', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Khoảng giá chốt kỳ vọng (VNĐ)')),
                ('don_gia_tham_khao', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Đơn giá tham khảo (VNĐ/m2)')),
                ('phan_tich_tiem_nang', models.TextField(blank=True, verbose_name='Phân tích tiềm năng và hạ tầng')),
                ('uu_diem_vi_tri', models.TextField(blank=True, verbose_name='Ưu điểm vị trí')),
                ('nhuoc_diem', models.TextField(blank=True, verbose_name='Nhược điểm/Hạn chế')),
                ('quy_hoach', models.TextField(blank=True, verbose_name='Quy hoạch/Kế hoạch sử dụng đất')),
                ('thoi_gian_khao_sat', models.DateField(blank=True, null=True, verbose_name='Thời gian khảo sát')),
                ('ghi_chu_them', models.TextField(blank=True, verbose_name='Ghi chú thêm')),
            ],
            options={
                'verbose_name': 'Bất động sản',
                'verbose_name_plural': 'Danh sách Bất động sản',
                'permissions': [('manage_batdongsan', 'Có thể quản lý toàn bộ Bất động sản')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(help_text='Phần hiển thị trên URL, không dấu, không khoảng trắng. VD: nhan-kim-cuong', max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Hình ảnh danh mục')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Các danh mục',
                'permissions': [('manage_category', 'Có thể quản lý toàn bộ Danh mục')],
            },
        ),
        migrations.CreateModel(
            name='ChucVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chuc_vu', models.CharField(max_length=100, unique=True, verbose_name='Tên chức vụ')),
            ],
            options={
                'verbose_name': 'Chức Vụ',
                'verbose_name_plural': 'Các Chức Vụ',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Nội dung tin nhắn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
            ],
            options={
                'verbose_name': 'Tin nhắn liên hệ',
                'verbose_name_plural': 'Các tin nhắn liên hệ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Chức danh')),
                ('slug', models.SlugField(blank=True, help_text='Phần hiển thị trên URL, sẽ được tự động tạo.', max_length=255, null=True, unique=True, verbose_name='Đường dẫn URL')),
                ('location', models.CharField(max_length=100, verbose_name='Địa điểm làm việc')),
                ('job_type', models.CharField(choices=[('full-time', 'Toàn thời gian'), ('part-time', 'Bán thời gian'), ('internship', 'Thực tập')], max_length=20, verbose_name='Loại hình công việc')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Mô tả công việc')),
                ('requirements', ckeditor.fields.RichTextField(verbose_name='Yêu cầu ứng viên')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang tuyển?')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đăng')),
            ],
            options={
                'verbose_name': 'Tin tuyển dụng',
                'verbose_name_plural': 'Các tin tuyển dụng',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='LoaiBatDongSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.CharField(max_length=100, unique=True, verbose_name='Tên loại BĐS')),
            ],
            options={
                'verbose_name': 'Loại Bất động sản',
                'verbose_name_plural': 'Các Loại Bất động sản',
                'ordering': ['ten_loai'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ giao hàng')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú của khách hàng')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng tiền')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('processing', 'Đang xử lý'), ('shipped', 'Đang giao hàng'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái đơn hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo đơn')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Các đơn hàng',
                'ordering': ['-created_at'],
                'permissions': [('manage_order', 'Có thể quản lý toàn bộ Đơn hàng')],
            },
        ),
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phong_ban', models.CharField(max_length=100, unique=True, verbose_name='Tên phòng ban')),
            ],
            options={
                'verbose_name': 'Phòng Ban',
                'verbose_name_plural': 'Các Phòng Ban',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề bài viết')),
                ('slug', models.SlugField(blank=True, help_text='Phần hiển thị trên URL, sẽ được tự động tạo.', max_length=255, null=True, unique=True, verbose_name='Đường dẫn URL')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Nội dung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Ảnh bìa')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đăng')),
                ('author', models.CharField(default='BJF', max_length=100, verbose_name='Tác giả')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề SEO')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Mô tả SEO')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Từ khóa (keywords)')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Các bài viết',
                'ordering': ['-published_date'],
                'permissions': [('manage_post', 'Có thể quản lý toàn bộ Bài viết')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(blank=True, help_text='Phần hiển thị trên URL, sẽ được tự động tạo.', max_length=255, null=True, unique=True, verbose_name='Đường dẫn URL')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mã sản phẩm (SKU)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá gốc (VND)')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá khuyến mãi (VND)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('is_available', models.BooleanField(default=True, verbose_name='Đang bán?')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Sản phẩm nổi bật?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Các sản phẩm',
                'permissions': [('manage_product', 'Có thể quản lý toàn bộ Sản phẩm')],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='BJF', max_length=255, verbose_name='Tên website')),
                ('site_description', models.TextField(blank=True, verbose_name='Mô tả trang web (SEO)')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon (icon trên tab)')),
                ('logo_text', models.CharField(default='BJF', max_length=255, verbose_name='Chữ trên Logo')),
                ('hero_background_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Ảnh nền banner chính (dự phòng)')),
                ('hero_title', models.CharField(default='Đẳng Cấp & Tinh Tế', max_length=255, verbose_name='Dòng tiêu đề chính')),
                ('hero_subtitle', models.CharField(default='Trong Từng Chế Tác', max_length=255, verbose_name='Dòng tiêu đề phụ (chữ vàng)')),
                ('hero_description', models.TextField(blank=True, verbose_name='Mô tả ngắn dưới tiêu đề')),
                ('slider_delay', models.PositiveIntegerField(default=5, verbose_name='Thời gian chuyển slide (giây)')),
                ('footer_address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ ở Footer')),
                ('footer_phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại ở Footer')),
                ('footer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email ở Footer')),
                ('footer_copyright', models.CharField(default='© 2025 Bản quyền thuộc về Công ty Vàng Bạc Đá Quý BJF.', max_length=255, verbose_name='Dòng copyright')),
            ],
            options={
                'verbose_name': 'Cài đặt chung',
                'verbose_name_plural': 'Cài đặt chung',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('title', models.CharField(help_text='Ví dụ: Doanh nhân, TP.HCM', max_length=100, verbose_name='Chức danh/Địa chỉ')),
                ('quote', models.TextField(verbose_name='Nội dung nhận xét')),
                ('image', models.ImageField(upload_to='testimonials/', verbose_name='Ảnh đại diện khách hàng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Nhận xét của khách hàng',
                'verbose_name_plural': 'Các nhận xét của khách hàng',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Hình ảnh')),
                ('is_main', models.BooleanField(default=False, verbose_name='Là ảnh chính?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Hình ảnh sản phẩm',
                'verbose_name_plural': 'Các hình ảnh sản phẩm',
                'ordering': ['order', 'is_main'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá tại thời điểm mua')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong đơn hàng',
                'verbose_name_plural': 'Các sản phẩm trong đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhan_vien', models.CharField(max_length=20, unique=True, verbose_name='Mã nhân viên')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('ngay_sinh', models.DateField(verbose_name='Ngày sinh')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('ngay_vao_lam', models.DateField(verbose_name='Ngày vào làm')),
                ('luong_co_ban', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Lương cơ bản (VND)')),
                ('trang_thai', models.CharField(choices=[('DLV', 'Đang làm việc'), ('DNV', 'Đã nghỉ việc'), ('TN', 'Tạm nghỉ')], default='DLV', max_length=3, verbose_name='Trạng thái làm việc')),
                ('chuc_vu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.chucvu', verbose_name='Chức vụ')),
                ('phong_ban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.phongban', verbose_name='Phòng ban')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Nhân Viên',
                'verbose_name_plural': 'Danh sách Nhân Viên',
                'permissions': [('manage_nhanvien', 'Có thể quản lý toàn bộ Nhân sự')],
            },
        ),
        migrations.CreateModel(
            name='HinhAnhBatDongSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bds/hien_trang/', verbose_name='Hình ảnh')),
                ('mo_ta', models.CharField(blank=True, max_length=255, verbose_name='Mô tả ngắn')),
                ('bat_dong_san', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hinh_anh', to='store.batdongsan', verbose_name='Bất động sản')),
            ],
            options={
                'verbose_name': 'Hình ảnh Bất động sản',
                'verbose_name_plural': 'Các Hình ảnh Bất động sản',
            },
        ),
        migrations.AddField(
            model_name='batdongsan',
            name='loai_bds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.loaibatdongsan', verbose_name='Loại BĐS'),
        ),
        migrations.AddField(
            model_name='batdongsan',
            name='nguoi_khao_sat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.nhanvien', verbose_name='Người khảo sát'),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_type', models.CharField(choices=[('gold', 'Vàng'), ('color', 'Màu sắc'), ('stone_type', 'Loại hạt')], max_length=50, verbose_name='Loại biến thể')),
                ('variation_name', models.CharField(max_length=100, verbose_name='Tên biến thể')),
                ('price_change', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thay đổi giá (VND)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='store.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm',
                'verbose_name_plural': 'Các biến thể sản phẩm',
                'unique_together': {('product', 'variation_type', 'variation_name')},
            },
        ),
        migrations.CreateModel(
            name='ChamCong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_cham_cong', models.DateField(verbose_name='Ngày chấm công')),
                ('trang_thai', models.CharField(choices=[('DL', 'Đi làm'), ('NP', 'Nghỉ phép'), ('VKP', 'Vắng không phép')], default='DL', max_length=3, verbose_name='Trạng thái')),
                ('gio_check_in', models.TimeField(blank=True, null=True, verbose_name='Giờ check-in')),
                ('gio_check_out', models.TimeField(blank=True, null=True, verbose_name='Giờ check-out')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Chấm Công',
                'verbose_name_plural': 'Dữ liệu Chấm Công',
                'unique_together': {('nhan_vien', 'ngay_cham_cong')},
            },
        ),
    ]
