# Generated by Django 5.2.5 on 2025-08-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='BJF', max_length=255, verbose_name='Tên website')),
                ('logo_text', models.CharField(default='BJF', max_length=255, verbose_name='Chữ trên Logo')),
                ('hero_title', models.CharField(default='Đẳng Cấp & Tinh Tế', max_length=255, verbose_name='Dòng tiêu đề chính')),
                ('hero_subtitle', models.CharField(default='Trong Từng Chế Tác', max_length=255, verbose_name='Dòng tiêu đề phụ (chữ vàng)')),
                ('hero_description', models.TextField(blank=True, verbose_name='Mô tả ngắn dưới tiêu đề')),
                ('footer_address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ ở Footer')),
                ('footer_phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại ở Footer')),
                ('footer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email ở Footer')),
                ('footer_copyright', models.CharField(default='© 2025 Bản quyền thuộc về Công ty Vàng Bạc Đá Quý BJF.', max_length=255, verbose_name='Dòng copyright')),
            ],
            options={
                'verbose_name': 'Cài đặt chung',
                'verbose_name_plural': 'Cài đặt chung',
            },
        ),
    ]
