# Generated by Django 5.2.5 on 2025-08-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon (icon trên tab)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Ảnh nền banner chính'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_description',
            field=models.TextField(blank=True, verbose_name='Mô tả trang web (SEO)'),
        ),
    ]
