# Generated by Django 5.2.5 on 2025-08-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_siteconfiguration_favicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Nội dung tin nhắn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
            ],
            options={
                'verbose_name': 'Tin nhắn liên hệ',
                'verbose_name_plural': 'Các tin nhắn liên hệ',
                'ordering': ['-created_at'],
            },
        ),
    ]
