# Generated by Django 5.2.5 on 2025-08-09 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ giao hàng')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú của khách hàng')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng tiền')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('processing', 'Đang xử lý'), ('shipped', 'Đang giao hàng'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái đơn hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo đơn')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Các đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Sản phẩm nổi bật?'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá khuyến mãi (VND)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mã sản phẩm (SKU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá gốc (VND)'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá tại thời điểm mua')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong đơn hàng',
                'verbose_name_plural': 'Các sản phẩm trong đơn hàng',
            },
        ),
    ]
