# Generated by Django 5.2.5 on 2025-08-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_product_is_featured_product_sale_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Hình ảnh banner')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề chính (tùy chọn)')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề phụ (tùy chọn)')),
                ('link', models.URLField(blank=True, verbose_name='Đường dẫn (tùy chọn)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị, số nhỏ hơn hiện trước', verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Các Banner',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Ảnh nền banner chính (dự phòng)'),
        ),
    ]
