# Generated by Django 5.2.5 on 2025-08-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_banner_alter_siteconfiguration_hero_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='slider_delay',
            field=models.PositiveIntegerField(default=5, verbose_name='Thời gian chuyển slide (giây)'),
        ),
    ]
