# Generated by Django 5.2.5 on 2025-08-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_siteconfiguration_slider_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Phần hiển thị trên URL, sẽ được tự động tạo.', max_length=255, null=True, unique=True, verbose_name='Đường dẫn URL'),
        ),
    ]
