# Generated by Django 5.2.5 on 2025-08-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', help_text='Phần hiển thị trên URL, sẽ được tự động tạo.', max_length=255, unique=True, verbose_name='Đường dẫn URL'),
            preserve_default=False,
        ),
    ]
