# Generated by Django 5.2.5 on 2025-08-09 09:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_post_keywords_post_meta_description_post_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Nội dung'),
        ),
    ]
