# Generated by Django 5.2.5 on 2025-08-09 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_type', models.CharField(choices=[('gold', 'Vàng'), ('color', 'Màu sắc'), ('stone_type', 'Loại hột')], max_length=50, verbose_name='Loại biến thể')),
                ('variation_name', models.CharField(max_length=100, verbose_name='Tên biến thể')),
                ('price_change', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thay đổi giá (VND)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='store.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm',
                'verbose_name_plural': 'Các biến thể sản phẩm',
                'unique_together': {('product', 'variation_type', 'variation_name')},
            },
        ),
    ]
