# Generated by Django 5.2.5 on 2025-08-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productvariation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='variation_type',
            field=models.CharField(choices=[('gold', 'Vàng'), ('color', 'Màu sắc'), ('stone_type', 'Loại hạt')], max_length=50, verbose_name='Loại biến thể'),
        ),
    ]
