# Generated by Django 5.2.5 on 2025-08-12 19:30

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_product_image_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Chức danh')),
                ('slug', models.SlugField(max_length=255, unique=True, help_text="Phần hiển thị trên URL, sẽ được tự động tạo.", verbose_name="Đường dẫn URL", null=True, blank=True)),
                ('location', models.CharField(max_length=100, verbose_name='Địa điểm làm việc')),
                ('job_type', models.CharField(choices=[('full-time', 'Toàn thời gian'), ('part-time', 'Bán thời gian'), ('internship', 'Thực tập')], max_length=20, verbose_name='Loại hình công việc')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Mô tả công việc')),
                ('requirements', ckeditor.fields.RichTextField(verbose_name='Yêu cầu ứng viên')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang tuyển?')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đăng')),
            ],
            options={
                'verbose_name': 'Tin tuyển dụng',
                'verbose_name_plural': 'Các tin tuyển dụng',
                'ordering': ['-published_date'],
            },
        ),
    ]