# Generated by Django 4.2.23 on 2025-08-28 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0017_auto_20250812_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Câu Chuyện Về BJF', max_length=200, verbose_name='Tiêu đề chính')),
                ('hero_subtitle', models.CharField(default='Nơi mỗi tuyệt tác không chỉ là trang sức, mà là di sản của đam mê và sự tinh xảo.', max_length=300, verbose_name='Tiêu đề phụ')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Ảnh nền Hero')),
                ('philosophy_tagline', models.CharField(default='Triết Lý Của Chúng Tôi', max_length=100, verbose_name='Dòng giới thiệu Triết lý')),
                ('philosophy_title', models.CharField(default='Tôn Vinh Vẻ Đẹp Vĩnh Cửu', max_length=200, verbose_name='Tiêu đề Triết lý')),
                ('philosophy_content', models.TextField(default='Tại BJF, chúng tôi tin rằng trang sức là ngôn ngữ của cảm xúc...', verbose_name='Nội dung Triết lý')),
                ('philosophy_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Ảnh Triết lý')),
                ('history_title', models.CharField(default='Dấu Ấn Qua Từng Thời Kỳ', max_length=200, verbose_name='Tiêu đề Lịch sử')),
                ('history_subtitle', models.CharField(default='Hơn hai thập kỷ không ngừng nỗ lực để xây dựng một thương hiệu trang sức Việt Nam uy tín và đẳng cấp.', max_length=300, verbose_name='Tiêu đề phụ Lịch sử')),
                ('milestone1_year', models.CharField(default='2005: Khởi Đầu Đam Mê', max_length=50, verbose_name='Cột mốc 1 - Năm & Tiêu đề')),
                ('milestone1_text', models.TextField(default='BJF ra đời từ một xưởng chế tác nhỏ...', verbose_name='Cột mốc 1 - Nội dung')),
                ('milestone1_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Cột mốc 1 - Ảnh')),
                ('milestone2_year', models.CharField(default='2015: Khẳng Định Vị Thế', max_length=50, verbose_name='Cột mốc 2 - Năm & Tiêu đề')),
                ('milestone2_text', models.TextField(default='Trở thành một trong những thương hiệu được tin cậy hàng đầu...', verbose_name='Cột mốc 2 - Nội dung')),
                ('milestone2_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Cột mốc 2 - Ảnh')),
                ('milestone3_year', models.CharField(default='2025: Vươn Ra Thế Giới', max_length=50, verbose_name='Cột mốc 3 - Năm & Tiêu đề')),
                ('milestone3_text', models.TextField(default='Ra mắt nền tảng thương mại điện tử...', verbose_name='Cột mốc 3 - Nội dung')),
                ('milestone3_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Cột mốc 3 - Ảnh')),
                ('craftsmanship_title', models.CharField(default='Nghệ Thuật Chế Tác Đỉnh Cao', max_length=200, verbose_name='Tiêu đề Chế tác')),
                ('craftsmanship_subtitle', models.CharField(default='Mỗi sản phẩm là một bản giao hưởng của vật liệu quý hiếm và bàn tay tài hoa của nghệ nhân.', max_length=300, verbose_name='Tiêu đề phụ Chế tác')),
            ],
            options={
                'verbose_name': 'Trang Về Chúng Tôi',
            },
        ),
        migrations.CreateModel(
            name='ActionButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_type', models.CharField(choices=[('zalo', 'Zalo'), ('phone', 'Gọi điện')], max_length=10, verbose_name='Loại nút')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Nút hành động',
                'verbose_name_plural': 'Các nút hành động',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BatDongSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tai_san', models.CharField(max_length=50, unique=True, verbose_name='ID tài sản')),
                ('dia_chi', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('google_maps_link', models.URLField(blank=True, null=True, verbose_name='Link Google Maps')),
                ('chi_tiet_su_dung_dat', models.CharField(help_text='Ví dụ: Đất thổ cư 5100 m2', max_length=255, verbose_name='Chi tiết sử dụng đất')),
                ('mat_tien', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mặt tiền (m)')),
                ('chieu_sau', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chiều sâu (m)')),
                ('huong', models.CharField(blank=True, max_length=50, verbose_name='Hướng')),
                ('phap_ly', models.CharField(default='Sổ đỏ/Sổ hồng', max_length=100, verbose_name='Pháp lý')),
                ('tinh_trang_xay_dung', models.CharField(default='Đất trống', max_length=100, verbose_name='Tình trạng xây dựng')),
                ('hien_trang_su_dung', models.TextField(blank=True, verbose_name='Hiện trạng sử dụng')),
                ('gia_rao_cam_co', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Giá chủ nhà rao cầm cố (VNĐ)')),
                ('gia_chot_ky_vong', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Khoảng giá chốt kỳ vọng (VNĐ)')),
                ('don_gia_tham_khao', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Đơn giá tham khảo (VNĐ/m2)')),
                ('phan_tich_tiem_nang', models.TextField(blank=True, verbose_name='Phân tích tiềm năng và hạ tầng')),
                ('uu_diem_vi_tri', models.TextField(blank=True, verbose_name='Ưu điểm vị trí')),
                ('nhuoc_diem', models.TextField(blank=True, verbose_name='Nhược điểm/Hạn chế')),
                ('quy_hoach', models.TextField(blank=True, verbose_name='Quy hoạch/Kế hoạch sử dụng đất')),
                ('thoi_gian_khao_sat', models.DateField(blank=True, null=True, verbose_name='Thời gian khảo sát')),
                ('ghi_chu_them', models.TextField(blank=True, verbose_name='Ghi chú thêm')),
            ],
            options={
                'verbose_name': 'Bất động sản',
                'verbose_name_plural': 'Danh sách Bất động sản',
                'permissions': [('manage_batdongsan', 'Có thể quản lý toàn bộ Bất động sản')],
            },
        ),
        migrations.CreateModel(
            name='ChucVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chuc_vu', models.CharField(max_length=100, unique=True, verbose_name='Tên chức vụ')),
            ],
            options={
                'verbose_name': 'Chức Vụ',
                'verbose_name_plural': 'Các Chức Vụ',
            },
        ),
        migrations.CreateModel(
            name='LoaiBatDongSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.CharField(max_length=100, unique=True, verbose_name='Tên loại BĐS')),
            ],
            options={
                'verbose_name': 'Loại Bất động sản',
                'verbose_name_plural': 'Các Loại Bất động sản',
            },
        ),
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phong_ban', models.CharField(max_length=100, unique=True, verbose_name='Tên phòng ban')),
            ],
            options={
                'verbose_name': 'Phòng Ban',
                'verbose_name_plural': 'Các Phòng Ban',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('title', models.CharField(help_text='Ví dụ: Doanh nhân, TP.HCM', max_length=100, verbose_name='Chức danh/Địa chỉ')),
                ('quote', models.TextField(verbose_name='Nội dung nhận xét')),
                ('image', models.ImageField(upload_to='testimonials/', verbose_name='Ảnh đại diện khách hàng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Nhận xét của khách hàng',
                'verbose_name_plural': 'Các nhận xét của khách hàng',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order'], 'permissions': [('manage_banner', 'Có thể quản lý toàn bộ Banner')], 'verbose_name': 'Banner', 'verbose_name_plural': 'Các Banner'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('manage_category', 'Có thể quản lý toàn bộ Danh mục')], 'verbose_name': 'Danh mục', 'verbose_name_plural': 'Các danh mục'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('manage_order', 'Có thể quản lý toàn bộ Đơn hàng')], 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Các đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date'], 'permissions': [('manage_post', 'Có thể quản lý toàn bộ Bài viết')], 'verbose_name': 'Bài viết', 'verbose_name_plural': 'Các bài viết'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('manage_product', 'Có thể quản lý toàn bộ Sản phẩm')], 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Các sản phẩm'},
        ),
        migrations.AddField(
            model_name='banner',
            name='file_type',
            field=models.CharField(choices=[('image', 'Hình ảnh'), ('video', 'Video')], default='image', max_length=10, verbose_name='Loại banner'),
        ),
        migrations.AddField(
            model_name='banner',
            name='video_url',
            field=models.URLField(blank=True, help_text="Dán link EMBED vào đây nếu loại banner là 'Video'. Ví dụ: https://www.youtube.com/embed/your_video_id", null=True, verbose_name='Đường dẫn Video (YouTube/Vimeo Embed)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text="Tải lên nếu loại banner là 'Hình ảnh'.", null=True, upload_to='banners/', verbose_name='Hình ảnh banner'),
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhan_vien', models.CharField(max_length=20, unique=True, verbose_name='Mã nhân viên')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('ngay_sinh', models.DateField(verbose_name='Ngày sinh')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('ngay_vao_lam', models.DateField(verbose_name='Ngày vào làm')),
                ('luong_co_ban', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Lương cơ bản (VND)')),
                ('trang_thai', models.CharField(choices=[('DLV', 'Đang làm việc'), ('DNV', 'Đã nghỉ việc'), ('TN', 'Tạm nghỉ')], default='DLV', max_length=3, verbose_name='Trạng thái làm việc')),
                ('chuc_vu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.chucvu', verbose_name='Chức vụ')),
                ('phong_ban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.phongban', verbose_name='Phòng ban')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Nhân Viên',
                'verbose_name_plural': 'Danh sách Nhân Viên',
                'permissions': [('manage_nhanvien', 'Có thể quản lý toàn bộ Nhân sự')],
            },
        ),
        migrations.CreateModel(
            name='HinhAnhBatDongSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bds/hien_trang/', verbose_name='Hình ảnh')),
                ('mo_ta', models.CharField(blank=True, max_length=255, verbose_name='Mô tả ngắn')),
                ('bat_dong_san', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hinh_anh', to='store.batdongsan', verbose_name='Bất động sản')),
            ],
            options={
                'verbose_name': 'Hình ảnh Bất động sản',
                'verbose_name_plural': 'Các Hình ảnh Bất động sản',
            },
        ),
        migrations.AddField(
            model_name='batdongsan',
            name='loai_bds',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.loaibatdongsan', verbose_name='Loại BĐS'),
        ),
        migrations.AddField(
            model_name='batdongsan',
            name='nguoi_khao_sat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.nhanvien', verbose_name='Người khảo sát'),
        ),
        migrations.CreateModel(
            name='ChamCong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_cham_cong', models.DateField(verbose_name='Ngày chấm công')),
                ('trang_thai', models.CharField(choices=[('DL', 'Đi làm'), ('NP', 'Nghỉ phép'), ('VKP', 'Vắng không phép')], default='DL', max_length=3, verbose_name='Trạng thái')),
                ('gio_check_in', models.TimeField(blank=True, null=True, verbose_name='Giờ check-in')),
                ('gio_check_out', models.TimeField(blank=True, null=True, verbose_name='Giờ check-out')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Chấm Công',
                'verbose_name_plural': 'Dữ liệu Chấm Công',
                'unique_together': {('nhan_vien', 'ngay_cham_cong')},
            },
        ),
    ]
