# Generated by Django 4.2.23 on 2025-08-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_aboutpage_actionbutton_batdongsan_chucvu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batdongsan',
            name='loai_bds',
            field=models.CharField(default='Đất nền', max_length=100, verbose_name='Loại BĐS'),
        ),
        migrations.DeleteModel(
            name='LoaiBatDongSan',
        ),
    ]
