# Generated by Django 4.2.23 on 2025-08-28 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_batdongsan_loai_bds_delete_loaibatdongsan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiBatDongSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.CharField(max_length=100, unique=True, verbose_name='Tên loại BĐS')),
            ],
            options={
                'verbose_name': 'Loại Bất động sản',
                'verbose_name_plural': 'Các Loại Bất động sản',
                'ordering': ['ten_loai'],
            },
        ),
        migrations.AlterField(
            model_name='batdongsan',
            name='loai_bds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.loaibatdongsan', verbose_name='Loại BĐS'),
        ),
    ]
